Algoritmo "testerepita"
// Disciplina  :  [Linguagem e Lógica de Programação] 
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 19/01/2019
Var
// Seção de Declarações das variáveis
cont : inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
cont <- 0
repita
      escreval("Aguarde...")
      cont <- cont + 1
ate cont = 10


Fimalgoritmo